version: "3.3"
services:
    openempi:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: openempi
        ports:
            - "8080:8080"
        stdin_open: true
        tty: true